### ISSUE TITLE
Sharp Crystal

### ISSUE THREAD

**Issue by hunterboerner** [HeisenBugDev/QuantumCraft-old#2]
When you put a crystal in an extractor, all the remaining energy gets sucked out and you are left with a shariper material

**Comment by sammko** [comment]
so make the depleted crystal like sharpened? or maybe depleted shards when you crush the crystal?

**Comment by hunterboerner** [comment]
How would the crystal be crushed

On Mon, Jan 28, 2013 at 7:23 AM, sammko notifications@github.com wrote:

> so make the depleted crystal like sharpened? or maybe depleted shards when
> you crush the crystal?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sammko/QuantumCraft/issues/2#issuecomment-12781282.

## 

Theron Boerner
Theronsminecraft.com

## 512-626-7620

**Comment by sammko** [comment]
macerator / rock crusher
without mods idk

**Comment by hunterboerner** [comment]
Ok, that should work

Edit: Gonna leave this thread open until implemented
