### ISSUE TITLE
GUI ShiftClick crash

### ISSUE THREAD

**Issue by sammko** [HeisenBugDev/QuantumCraft-old#8]
crash when shifclicking from inv to gui or vice versa.
its a stackoverflow.

**Comment by hunterboerner** [comment]
This was caused to leaving out a method, and can be fixed easily but will have problems. I can make it return null so the problem doesn't occur, however shift clicking at all won't work. We can look at the backpack mod code to fix this.

**Comment by hunterboerner** [comment]
temporary fixed by disabling shift clicking

**Comment by LordFokas** [comment]
It's really simple. I've done that too. I have a functional implementation of that.

here: https://github.com/LordFokas/StargateTech/blob/master/lordfokas/stargatetech/machine/ParticleIonizerContainer.java#L23

Feel free to use it... after all, it's open source.
